#
# Chef Server Config File
#
# Dynamically generated by Chef - local modifications will be replaced

log_level          :info
log_location       "/var/log/chef/server.log"
ssl_verify_mode    :verify_none
registration_url   "http://ubuntu.localdomain"
openid_url         "http://ubuntu.localdomain"
template_url       "http://ubuntu.localdomain"
remotefile_url     "http://ubuntu.localdomain"
search_url         "http://ubuntu.localdomain"

validation_token   "SgDiKE2FqEycHPErdrPO"

cookbook_path      [ "/srv/chef/site-cookbooks", "/srv/chef/cookbooks" ]

file_store_path    "/srv/chef/file_store"
file_cache_path    "/srv/chef/cache"
node_path          "/srv/chef/nodes"
openid_store_path  "/srv/chef/openid/store"
openid_cstore_path "/srv/chef/openid/cstore"
search_index_path  "/srv/chef/search_index"

# uncomment and modify to allow specific openid providers
#openid_providers   [ "https://ubuntu.localdomain", "https://chef", "myopenid.com" ]
# uncomment and modify to lock down openid identifiers, ie 'some_user.myopenid.com'
#authorized_openid_identifiers [ "" ]

Chef::Log::Formatter.show_time = true
